# 100 numpy exercises



Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np 

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
print(np.__version__)

1.19.0


In [7]:
print(np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
n = np.zeros((5,8))
print("%d bytes" % (n.size * n.itemsize))

320 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
n = np.zeros(10)
n[4] = 1
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
x = np.arange(10, 50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
x = np.arange(22, 33)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[22 23 24 25 26 27 28 29 30 31 32]
Reverse array:
[32 31 30 29 28 27 26 25 24 23 22]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
x = np.arange(9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
y = np.nonzero([1,2,0,0,4,0])
print(y)

(array([0, 1, 4], dtype=int32),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [22]:
x = np.eye(3)
print (x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [24]:
x = np.random.random((3,3,3))
print(x)

[[[0.67752121 0.11640496 0.92406307]
  [0.37195245 0.57436272 0.98536578]
  [0.54998026 0.92199593 0.90902423]]

 [[0.5824914  0.86631156 0.57983081]
  [0.50827999 0.27108129 0.9617109 ]
  [0.72946072 0.04291479 0.40833943]]

 [[0.85269843 0.07092542 0.83793315]
  [0.7128487  0.21705483 0.28153459]
  [0.82962598 0.42237893 0.83017433]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [25]:
x = np.random.random((10,10))
xmin , xmax = x.min() , x.max()
print("Min value", xmin)
print("Max value",xmax)

Min value 0.0016035934651892347
Max value 0.9945165984370459


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [26]:
x = np.random.random(30)
y = x.mean()
print(y)

0.5041628460778352


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [27]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [28]:
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [29]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [30]:

x = np.diag(1+np.arange(4), k = -1)
print (x)



[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [31]:
x = np.zeros ((8,8), dtype=int)
x[1::2, ::2]= 1
x[::2, 1::2] = 1
print (x)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [32]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [33]:
x= np.array([[0,1], [1,0]])
y = np.tile(x,(4,4))
print (y)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [34]:

x = np.random.random((5,5))
xmax, xmin = x.max(), x.min()
x= (x-xmin)/(xmax-xmin)
print (x)



[[0.64541801 0.11018762 0.78486802 0.00556101 0.04741286]
 [0.50251091 0.         1.         0.4800904  0.55983067]
 [0.21428158 0.68391277 0.14475366 0.22811065 0.11928051]
 [0.35124096 0.51482792 0.87045408 0.30252638 0.14504405]
 [0.36263691 0.87891325 0.51876208 0.38170697 0.5514685 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [35]:
x = np.dtype([("r", np.ubyte, 1),
              ("g", np.ubyte, 1),
              ("b", np.ubyte, 1),
              ("a", np.ubyte, 1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [37]:
x = np.arange(20).reshape((10, 2))
y = np.arange(10).reshape((2, 5))
np.dot(x, y)


array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113],
       [ 55,  76,  97, 118, 139],
       [ 65,  90, 115, 140, 165],
       [ 75, 104, 133, 162, 191],
       [ 85, 118, 151, 184, 217],
       [ 95, 132, 169, 206, 243]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [38]:
x = np.arange(11)
x[(x >= 3) & (x <= 8)] = -1


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [39]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [47]:
Z = np.arange(3)
x = Z**Z
print(x)
x = 2 << Z >> 2
print(x)
x = Z <- Z 
print(x)
x = 1j * Z
print(x)
x = Z/1/1
print(x)
x = Z < Z > Z 
print(x)

[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [48]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [49]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([-10.,   7.,   1., -10.,  -4.,   7.,  10.,   5.,  -3.,  -3.])

#### 30. How to find common values between two arrays? (★☆☆)

In [50]:
x = np.arange(0, 10)
y = np.arange(5, 15)
np.intersect1d(x, y)


array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [51]:
defaults = np.seterr(all="ignore")
x = np.ones(1) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [52]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) 

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [54]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-06-26
Today:  2020-06-27
Tomorrow:  2020-06-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [56]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [59]:
x = np.ones(3) * 1
y = np.ones(3) * 2
z = np.ones(3) * 3
np.add(x, y, out=y)
np.divide(x, 2, out=x)
np.negative(x, out=x)
np.multiply(x, y, out=x)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [61]:
x = np.random.uniform(-10, +10, 10)
x.astype(np.int32)
y=np.trunc(x)
print(y)

[-5. -3. -7.  1. -7. -8.  5.  8. -5.  5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [63]:
x = np.zeros((5, 5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [64]:
def gen_intr():
    for i in range(10):
        yield i
np.fromiter(gen_intr(), dtype=np.float32, count=-1)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [65]:
x = np.linspace(start=0, stop=11, num=10, endpoint=False)
print(x)

[0.  1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [68]:
x = np.random.random(size=10)
print(x.sort())

None


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [70]:
import time
begin_time = time.time()
x = np.arange(1000000)
np.sum(x)
end_time = time.time()
print(str(1000*(end_time - begin_time)))

begin_time2 = time.time()
x = np.arange(1000000)
np.add.reduce(x)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [73]:
A = np.arange(10)
B = np.arange(10)
x = np.array_equal(A, B)
print(x)

True


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
x = np.zeros(10)
x.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [74]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)


[1.00179625 0.69685722 1.00169589 0.76915133 0.82622778 0.72840758
 1.02087962 0.73108404 0.30437133 0.88618152]
[0.38386658 1.30985838 1.43130422 0.07774957 0.18059877 1.53314374
 0.69495594 1.36644808 1.13577526 0.71362019]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [4]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)


[0.31738741 0.18929088 0.30337055 0.59641935 0.         0.44689152
 0.51743602 0.70236089 0.67838216 0.52808237]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [5]:
w = np.zeros((10,10), [('x',float),('y',float)])
w['x'], w['y'] = np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
print(w)



[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [6]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
c = np.linalg.det(c)
print(c)

[[-8.81055894e+03  3.29520043e+02 -4.66389291e+05 -1.13149271e+05
   4.25672017e+02]
 [-1.50268331e+07 -2.78748454e+07 -2.32051552e+04 -6.62949634e+04
  -2.00129123e+05]
 [ 4.68809404e+02  6.80131671e+05 -2.79379985e+07  4.95938148e+06
  -2.07948304e+03]
 [ 6.41435863e+04 -1.24291383e+07  3.28080238e+04  2.47821146e+06
   2.01823049e+07]
 [ 3.44203147e+06 -1.03139660e+06  8.27052164e+07  1.63383562e+08
  -2.11061387e+05]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [7]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [11]:
np.set_printoptions()
x = np.zeros((25,25))
print(x)



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [12]:
x = np.arange(100)
v = np.random.uniform(0,20)
index = (np.abs(x-v)).argmin()
print(x[index])



9


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [13]:
x = np.zeros(10,[('position',[('x', float, 1),('y', float, 1)]),('color',[ ('r', float, 1),('g', float, 1),('b', float, 1)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [15]:
x = np.arange(10, dtype=np.int32)
x = x.astype(np.float32, copy=False)
print(x)



[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [19]:
y = open("missing.dat.txt")
x = np.genfromtxt(y, delimiter=",")
print(x)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [3]:
x  = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(x):
    print(index, value)
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [4]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [5]:
n = 10
p = 3
x = np.zeros((n,n))
np.put(x, np.random.choice(range(n*n), p, replace=False),1)
print (x)



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [6]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[ 0.17244028 -0.14991397  0.08792417 -0.44052281  0.38326891  0.13129539
   0.04063794 -0.12042068  0.17841428 -0.28312352]
 [-0.26849344  0.47585016 -0.03914089 -0.026297    0.58152972 -0.34764055
  -0.37643067 -0.24641887  0.22326361  0.02377793]
 [ 0.39417546  0.34852963  0.09953838  0.32699583 -0.0850716  -0.26223792
  -0.38576435 -0.01870514 -0.03407704 -0.38338325]
 [ 0.26011059 -0.10558643 -0.00751119  0.22263066  0.16471076 -0.23116071
  -0.31476663  0.3473633  -0.49362888  0.15783853]
 [-0.28959218 -0.02553379  0.10775343 -0.22436612  0.4283711   0.35011192
  -0.35655762  0.09023068  0.21817416 -0.29859158]]


#### 59. How to sort an array by the nth column? (★★☆)

In [7]:
x = np.random.randint(0,10,(3,3))
print(x)
print(x[x[:,1].argsort()])



[[8 4 0]
 [0 5 2]
 [7 7 8]]
[[8 4 0]
 [0 5 2]
 [7 7 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [8]:
x = np.random.randint(0,3,(3,10))
print((~x.any(axis=0)).any())



False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [9]:
X = np.random.uniform(0,1,10)
x = 0.5
y = X.flat[np.abs(X - x).argmin()]
print(y)



0.5423784067253264


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [10]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [11]:
class Arr(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

x = Arr(np.arange(10), "range_10")
print (x.name)


range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [20]:
A = np.ones(10)
I = np.random.randint(0,len(A),20)
A += np.bincount(I, minlength=len(A))
print(A)

[2. 5. 2. 2. 5. 3. 4. 3. 1. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [21]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [22]:
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

30.0


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [23]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.52942976 0.39411504 0.52995232 0.5375978  0.46864262 0.51756689
 0.37022212 0.52441991 0.44940022 0.57623191]


#### 69. How to get the diagonal of a dot product? (★★★)

In [24]:
x = np.random.randint(0,10,(3,3))
y = np.random.randint(0,10,(3,3))
np.diag(np.dot(x, y))

array([66, 45, 22])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [25]:
x = np.array([1,2,3,4,5])
y = 3
z = np.zeros(len(x) + (len(x)-1)*(y))
z[::y+1] = x
print(z)



[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [26]:
x = np.ones((5,5,3))
y = 2*np.ones((5,5))
print(x * y[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [28]:
x = np.arange(9).reshape(3,3)
x[[0,1]] = x[[1,0]]
print(x)



[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [29]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3, 19) ( 3, 24) ( 3, 66) ( 3, 72) ( 4, 45) ( 4, 70) (10, 16) (10, 82)
 (15, 74) (15, 82) (16, 82) (19, 72) (19, 73) (19, 97) (23, 46) (23, 53)
 (24, 66) (27, 75) (27, 96) (29, 40) (29, 56) (40, 56) (45, 70) (46, 53)
 (62, 86) (62, 92) (73, 97) (74, 82) (75, 96) (86, 92)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [30]:
x = np.bincount([1,1,2,3,4,4,6])
y = np.repeat(np.arange(len(x)), x)
print(x)



[0 2 1 1 2 0 1]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [32]:
def avge(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(avge(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [33]:

def roll(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = roll(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [34]:
x = np.random.randint(0,2,100)
print ('original: ')
print (x)
print('Negating a boolean: ')
print(np.logical_not(x, out=x))

x = np.random.uniform(-1.0,1.0,10)
print ('original: ')
print (x)
print ('Change the sign of float inplace: ')
print(np.negative(x, out=x))



original: 
[0 0 1 0 0 1 0 1 1 1 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1 0 0 0 0 1
 1 0 1 1 0 1 0 1 0 0 1 0 1 1 0 0 0 0 1 0 0 1 0 1 0 1]
Negating a boolean: 
[1 1 0 1 1 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 1 0 1 1 1 1 1
 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 1 0 0 1 1 1 1 0
 0 1 0 0 1 0 1 0 1 1 0 1 0 0 1 1 1 1 0 1 1 0 1 0 1 0]
original: 
[-0.21570456  0.89715186  0.96797738 -0.02788098  0.94657824  0.27467838
  0.85555383  0.74215868  0.54899756 -0.23327165]
Change the sign of float inplace: 
[ 0.21570456 -0.89715186 -0.96797738  0.02788098 -0.94657824 -0.27467838
 -0.85555383 -0.74215868 -0.54899756  0.23327165]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [41]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.31445002  3.6065226   1.58132025  6.39837362 10.05659894  0.47815524
  6.84257558  2.74449863  1.80298534  1.42994093]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [42]:
P0 = np.random.uniform(-10, 10, (5,2))
P1 = np.random.uniform(-10,10,(5,2))
p = np.random.uniform(-10, 10, (5,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 7.7998415  16.19869611  7.74551371  5.5404171  13.10947413]
 [10.14118244  0.64975334  0.91543987 14.17619588  4.77407183]
 [12.36049336  3.80010597  0.13616026 13.39171325  6.93097674]
 [ 1.31395837  7.09493621  9.84403564  3.4268914   6.80062556]
 [ 2.80679319 11.3526745   6.25260219 19.53367051  2.2715571 ]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [43]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 2 5 3 8 1 7 7 3 4]
 [3 7 8 3 6 1 2 6 5 6]
 [7 1 8 1 0 8 7 8 9 6]
 [7 2 1 6 8 5 4 7 5 6]
 [2 5 8 7 7 1 4 5 7 1]
 [1 0 4 6 8 6 4 8 1 7]
 [7 0 7 5 8 2 2 7 9 7]
 [8 5 4 4 0 7 9 2 5 4]
 [3 4 8 2 7 4 3 2 1 6]
 [1 6 5 3 6 5 4 3 3 3]]
[[0 0 0 0 0]
 [0 8 2 5 3]
 [0 3 7 8 3]
 [0 7 1 8 1]
 [0 7 2 1 6]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [44]:
x = np.arange(1,15,dtype=int)
def roll(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
y = roll(x, 4)
print ('original: ')
print (x)
print ('after strides: ')
print(y)

original: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
after strides: 
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [45]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print (rank)

10


#### 83. How to find the most frequent value in an array?

In [46]:
x = np.random.randint(0,10,50)
print (x)
print('rank:', np.bincount(x).argmax())

[5 5 9 0 3 6 7 7 1 7 8 5 5 4 0 4 8 5 7 2 5 1 1 1 7 8 8 7 6 7 3 0 8 5 7 7 1
 0 1 3 3 9 8 9 6 6 3 0 8 6]
rank: 7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [47]:
Z = np.random.randint(0,5,(6,6))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 3 1]
   [0 4 2]
   [3 0 1]]

  [[3 1 0]
   [4 2 1]
   [0 1 4]]

  [[1 0 2]
   [2 1 4]
   [1 4 3]]

  [[0 2 1]
   [1 4 4]
   [4 3 2]]]


 [[[0 4 2]
   [3 0 1]
   [0 1 0]]

  [[4 2 1]
   [0 1 4]
   [1 0 2]]

  [[2 1 4]
   [1 4 3]
   [0 2 1]]

  [[1 4 4]
   [4 3 2]
   [2 1 4]]]


 [[[3 0 1]
   [0 1 0]
   [1 1 3]]

  [[0 1 4]
   [1 0 2]
   [1 3 2]]

  [[1 4 3]
   [0 2 1]
   [3 2 1]]

  [[4 3 2]
   [2 1 4]
   [2 1 4]]]


 [[[0 1 0]
   [1 1 3]
   [0 1 2]]

  [[1 0 2]
   [1 3 2]
   [1 2 3]]

  [[0 2 1]
   [3 2 1]
   [2 3 2]]

  [[2 1 4]
   [2 1 4]
   [3 2 3]]]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [49]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4  6  8  5  9]
 [ 6  3 13 12  7]
 [ 8 13  7 42 10]
 [ 5 12 42  0 13]
 [ 9  7 10 13  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [50]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [51]:
x = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], k), axis=0),np.arange(0, x.shape[1], k), axis=1)
print ('input array')
print (x)
print ('block sum')
print (S)



input array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
block sum
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [52]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [53]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [54]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [55]:
Z = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [61]:
x = np.random.randint(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)


1.26 µs ± 35.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
218 ns ± 2.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


ValueError: einstein sum subscripts string contains too many subscripts for operand 0

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [62]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)


[0 1 2 3 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [63]:
Z = np.random.randint(0,5,(10,3))
print(Z)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 4 2]
 [1 4 0]
 [3 1 2]
 [1 4 4]
 [4 2 2]
 [4 3 3]
 [1 4 4]
 [2 2 2]
 [1 0 4]
 [3 4 2]]
[[4 4 2]
 [1 4 0]
 [3 1 2]
 [1 4 4]
 [4 2 2]
 [4 3 3]
 [1 4 4]
 [1 0 4]
 [3 4 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [64]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [65]:
uZ = np.unique(Z, axis=0)
print(uZ)

[[1 0 4]
 [1 4 0]
 [1 4 4]
 [2 2 2]
 [3 1 2]
 [3 4 2]
 [4 2 2]
 [4 3 3]
 [4 4 2]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [67]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)      
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)   
np.einsum('i,j->ij', A, B) 

array([[0.01759785, 0.01815352, 0.00251286, 0.01637945, 0.01680314,
        0.01024361, 0.01981308, 0.00983257, 0.01026174, 0.01143373],
       [0.50090976, 0.51672661, 0.07152676, 0.46622902, 0.47828909,
        0.29157682, 0.5639646 , 0.27987689, 0.29209298, 0.32545267],
       [0.72885321, 0.75186767, 0.10407566, 0.6783907 , 0.69593881,
        0.42426146, 0.82060172, 0.40723737, 0.42501249, 0.47355281],
       [0.49878784, 0.51453769, 0.07122377, 0.46425402, 0.476263  ,
        0.29034167, 0.56157558, 0.2786913 , 0.29085564, 0.32407401],
       [0.77658515, 0.8011068 , 0.11089148, 0.72281788, 0.74151521,
        0.45204595, 0.87434218, 0.43390697, 0.45284617, 0.50456535],
       [0.53260898, 0.54942678, 0.07605321, 0.49573353, 0.5085568 ,
        0.31002876, 0.59965414, 0.29758842, 0.31057758, 0.34604839],
       [0.43726222, 0.45106932, 0.0624383 , 0.40698815, 0.41751583,
        0.25452794, 0.49230507, 0.24431465, 0.25497851, 0.28409939],
       [0.72130879, 0.74408502, 0.1029983

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

array([[0.6755594 , 0.5713    , 0.23732359, 0.59575838, 0.64336583,
        0.18971353, 0.33505656, 0.10383099, 0.47787272, 0.38752267],
       [0.23611275, 0.19967335, 0.08294626, 0.20822173, 0.22486087,
        0.06630621, 0.11710462, 0.03628966, 0.16701987, 0.13544189],
       [0.39857178, 0.33706001, 0.14001801, 0.35149016, 0.37957797,
        0.11192866, 0.19767927, 0.06125901, 0.28193906, 0.22863364],
       [0.29855315, 0.2524773 , 0.10488153, 0.26328631, 0.28432569,
        0.08384099, 0.14807313, 0.04588652, 0.21118855, 0.17125972],
       [0.74358269, 0.62882522, 0.26122013, 0.65574636, 0.70814749,
        0.20881612, 0.36879401, 0.11428592, 0.52599059, 0.42654303],
       [0.1351471 , 0.11428978, 0.04747709, 0.11918273, 0.1287067 ,
        0.03795259, 0.06702878, 0.02077161, 0.09559946, 0.07752474],
       [0.02474832, 0.0209289 , 0.00869407, 0.02182491, 0.02356895,
        0.00694993, 0.0122744 , 0.00380373, 0.01750631, 0.01419644],
       [0.48645578, 0.41138083, 0.1708916

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [68]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],[2.0, 0.0, 1.0, 1.0],[1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [69]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.19764731  0.19106006]
